/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteEstofaria;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrei
 */
public class AdicionaServico extends javax.swing.JFrame {
    ArrayList<Cliente> listaClientes;
    int posicao;
    AdicionaContato addContato;
    Ficha ficha;
    Principal principal;
    ProcurarCliente procura;
    ListarClientes listar;
    Cliente cliente;
    /**
     * Creates new form JanelaAdicionaServico
     */
    public AdicionaServico(Principal janela,AdicionaContato add,Ficha fi,ProcurarCliente pro,ListarClientes lis,Cliente cliente,int pos,ArrayList<Cliente> listaC) {
        initComponents();
        this.listaClientes = listaC;
        this.posicao = pos;
        this.ficha = fi;
        this.procura = pro;
        this.cliente = cliente;
        this.addContato = add;
        this.principal = janela;
        this.listar = lis;
        
        this.setLocationRelativeTo(addContato);
        this.textoNome.setText(cliente.getNome());
        this.textoBairro.setText(cliente.getBairro());
        this.textoCel.setText(cliente.getCelular());
        this.textoTel.setText(cliente.getTelefone());
        this.textoEnd.setText(cliente.getEndereco());
        this.textoNota.setText(cliente.getAnotacao());
        this.textoID.setText(cliente.getID());
        this.textoAddEm.setText("Adicionado em: "+cliente.getDataAdd());
        
        this.setSize(560, 660);
        ImageIcon img = new ImageIcon("src/Icons/iconsofa.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDetalhes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textoValorCobrado = new javax.swing.JTextField();
        botaoVoltarAddServico = new javax.swing.JButton();
        textoValorGasto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botaoAddServico = new javax.swing.JButton();
        painelAddServico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoEnd = new javax.swing.JLabel();
        textoTel = new javax.swing.JLabel();
        textoNota = new javax.swing.JLabel();
        textoCel = new javax.swing.JLabel();
        textoBairro = new javax.swing.JLabel();
        textoID = new javax.swing.JLabel();
        textoAddEm = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        seletorDataAtual = new javax.swing.JRadioButton();
        comboDia = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comboAno = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Adicionar Serviço");
        setPreferredSize(new java.awt.Dimension(560, 630));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(textoServico);
        textoServico.setBounds(130, 265, 410, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Serviço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 265, 72, 31);

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 3, 46)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Adicionar Serviço");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, 18, 580, 58);

        textoDetalhes.setColumns(20);
        textoDetalhes.setLineWrap(true);
        textoDetalhes.setRows(5);
        jScrollPane1.setViewportView(textoDetalhes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 392, 410, 179);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor Cobrado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 305, 112, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Detalhes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 392, 119, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 88, 560, 10);

        textoValorCobrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoValorCobradoKeyTyped(evt);
            }
        });
        getContentPane().add(textoValorCobrado);
        textoValorCobrado.setBounds(130, 305, 149, 31);

        botaoVoltarAddServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Seta Voltar.png"))); // NOI18N
        botaoVoltarAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarAddServicoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltarAddServico);
        botaoVoltarAddServico.setBounds(130, 582, 81, 39);

        textoValorGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoValorGastoKeyTyped(evt);
            }
        });
        getContentPane().add(textoValorGasto);
        textoValorGasto.setBounds(392, 307, 148, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor Gasto");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(291, 307, 91, 31);

        botaoAddServico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAddServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/oie_transparent.png"))); // NOI18N
        botaoAddServico.setText("Adicionar");
        botaoAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddServicoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAddServico);
        botaoAddServico.setBounds(400, 582, 140, 39);

        painelAddServico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ficha do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Nome:");

        jLabel6.setText("Endereço:");

        jLabel9.setText("Bairro:");

        jLabel10.setText("Telefone:");

        jLabel11.setText("Celular:");

        jLabel12.setText("Identificação:");

        jLabel13.setText("Anotação:");

        textoNome.setText("jLabel14");

        textoEnd.setText("jLabel14");

        textoTel.setText("jLabel15");

        textoNota.setText("jLabel16");

        textoCel.setText("jLabel17");

        textoBairro.setText("jLabel18");

        textoID.setText("jLabel19");

        javax.swing.GroupLayout painelAddServicoLayout = new javax.swing.GroupLayout(painelAddServico);
        painelAddServico.setLayout(painelAddServicoLayout);
        painelAddServicoLayout.setHorizontalGroup(
            painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddServicoLayout.createSequentialGroup()
                .addGroup(painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAddServicoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelAddServicoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(painelAddServicoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAddServicoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelAddServicoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelAddServicoLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))))
            .addGroup(painelAddServicoLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAddServicoLayout.setVerticalGroup(
            painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAddServicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(textoNome)
                    .addComponent(textoID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(textoEnd)
                    .addComponent(textoBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(textoTel)
                    .addComponent(textoCel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAddServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textoNota))
                .addContainerGap())
        );

        getContentPane().add(painelAddServico);
        painelAddServico.setBounds(10, 110, 530, 135);

        textoAddEm.setForeground(new java.awt.Color(153, 255, 255));
        textoAddEm.setText("Adicionado em: 12 de Dezembro de 2016 -- Terça 22:25");
        getContentPane().add(textoAddEm);
        textoAddEm.setBounds(210, 94, 340, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 345, 36, 35);

        seletorDataAtual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seletorDataAtual.setForeground(new java.awt.Color(255, 255, 255));
        seletorDataAtual.setText("Usar Data Atual");
        seletorDataAtual.setOpaque(false);
        seletorDataAtual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seletorDataAtualMouseClicked(evt);
            }
        });
        getContentPane().add(seletorDataAtual);
        seletorDataAtual.setBounds(418, 353, 122, 23);

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(comboDia);
        comboDia.setBounds(130, 355, 83, 20);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(comboMes);
        comboMes.setBounds(223, 355, 94, 20);

        comboAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(comboAno);
        comboAno.setBounds(328, 355, 84, 20);

        jPanel1.setPreferredSize(new java.awt.Dimension(560, 630));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 650);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarAddServicoActionPerformed
        this.dispose();
        if(addContato!=null)
        addContato.setVisible(true);
        else if(ficha!=null)
        ficha.setVisible(true);
        else if(listar !=null)
        listar.setVisible(true);
        else
        procura.setVisible(true);
    }//GEN-LAST:event_botaoVoltarAddServicoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void seletorDataAtualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seletorDataAtualMouseClicked
        if(seletorDataAtual.isSelected()){
            comboDia.setEnabled(false);
            comboMes.setEnabled(false);
            comboAno.setEnabled(false);
        }else{
            comboDia.setEnabled(true);
            comboMes.setEnabled(true);
            comboAno.setEnabled(true);
        }
    }//GEN-LAST:event_seletorDataAtualMouseClicked

    private void botaoAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddServicoActionPerformed
        
        if(textoServico.getText().trim().equals(""))
          JOptionPane.showMessageDialog(this,"Serviço não inserido!","Erro",JOptionPane.ERROR_MESSAGE);
        else{
        int n = JOptionPane.showConfirmDialog(this,"Confirmar serviço?","Confirmar?",JOptionPane.YES_NO_OPTION);            
                if(n==0){
                        String dataAtual="";
                        if(seletorDataAtual.isSelected()){
                            Data data = new Data();
                            dataAtual = data.getDataAtual();
                        }else{
                            dataAtual = comboDia.getSelectedItem().toString() +" de "+ comboMes.getSelectedItem().toString() +" de "+ comboAno.getSelectedItem().toString();
                        }
                    
                    Servico servico = new Servico(textoServico.getText(),textoValorCobrado.getText(),textoValorGasto.getText(),dataAtual,textoDetalhes.getText());
                    
                    cliente.addServico(servico);
                    
                    if(posicao==-1)
                       listaClientes.add(cliente);
                    else
                        listaClientes.set(posicao, cliente);
                    
                    principal.clientes = listaClientes;
                    
                    ManipuladorDeArquivos manip = new ManipuladorDeArquivos();
                    manip.salvarLista(listaClientes);
                    
                    this.dispose();
                    
                    
                   
                    principal.atualizaUltimosClientes();
                    principal.setVisible(true);
                
                }
               }
    }//GEN-LAST:event_botaoAddServicoActionPerformed

    private void textoValorCobradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoValorCobradoKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_textoValorCobradoKeyTyped

    private void textoValorGastoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoValorGastoKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_textoValorGastoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JanelaAdicionaServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddServico;
    private javax.swing.JButton botaoVoltarAddServico;
    private javax.swing.JComboBox<String> comboAno;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel painelAddServico;
    private javax.swing.JRadioButton seletorDataAtual;
    private javax.swing.JLabel textoAddEm;
    private javax.swing.JLabel textoBairro;
    private javax.swing.JLabel textoCel;
    private javax.swing.JTextArea textoDetalhes;
    private javax.swing.JLabel textoEnd;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoNota;
    private javax.swing.JTextField textoServico;
    private javax.swing.JLabel textoTel;
    private javax.swing.JTextField textoValorCobrado;
    private javax.swing.JTextField textoValorGasto;
    // End of variables declaration//GEN-END:variables
}
