
package PacoteEstofaria;

import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Andrei
 */
public class AdicionaContato extends javax.swing.JFrame {
    public Principal principal;
    /**
     * Creates new form AdicionaContatoJanela
     */
    public AdicionaContato(Principal princ) {
        initComponents();
        principal = princ;
        
        this.setSize(491, 646);
        ImageIcon img = new ImageIcon("src/Icons/iconsofa.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoRGCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoEnd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botaoAddCliente = new javax.swing.JButton();
        textoTel = new javax.swing.JTextField();
        textoNome = new javax.swing.JTextField();
        textoCel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoNota = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        botaoVoltar = new javax.swing.JButton();
        textoBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Adicionar Cliente.");
        setBackground(new java.awt.Color(0, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(51, 51, 255));
        setLocation(getLocation());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 152, 113, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Celular");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 194, 113, 22);

        textoRGCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoRGCPFKeyTyped(evt);
            }
        });
        getContentPane().add(textoRGCPF);
        textoRGCPF.setBounds(133, 318, 340, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 236, 113, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Anotação");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 360, 119, 22);
        getContentPane().add(textoEnd);
        textoEnd.setBounds(133, 235, 340, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Identificação");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 319, 119, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 109, 113, 31);

        botaoAddCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/oie_transparent.png"))); // NOI18N
        botaoAddCliente.setText("Adicionar");
        botaoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAddCliente);
        botaoAddCliente.setBounds(342, 545, 131, 39);

        textoTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTelKeyTyped(evt);
            }
        });
        getContentPane().add(textoTel);
        textoTel.setBounds(133, 151, 340, 31);
        getContentPane().add(textoNome);
        textoNome.setBounds(133, 109, 340, 31);

        textoCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoCelKeyTyped(evt);
            }
        });
        getContentPane().add(textoCel);
        textoCel.setBounds(133, 193, 340, 31);

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 3, 46)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Adicionar Cliente");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-9, 18, 500, 60);

        textoNota.setColumns(20);
        textoNota.setLineWrap(true);
        textoNota.setRows(5);
        jScrollPane1.setViewportView(textoNota);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(133, 360, 340, 179);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 88, 491, 10);

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Seta Voltar.png"))); // NOI18N
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(133, 545, 80, 39);
        getContentPane().add(textoBairro);
        textoBairro.setBounds(133, 277, 340, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bairro");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 277, 105, 22);

        jPanel1.setLayout(null);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 600, 490, 10);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 490, 620);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 620);

        getAccessibleContext().setAccessibleName("Adicionar Cliente");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Ação ao clicar em adicionar cliente.(confirmação)
    private void botaoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddClienteActionPerformed
    if(textoNome.getText().trim().equals(""))
        JOptionPane.showMessageDialog(this,"Nome não inserido!","Erro",JOptionPane.ERROR_MESSAGE);
    else{
        int choice = JOptionPane.showOptionDialog(this, //Component parentComponent
                                       "Deseja confirmar o registro de "+textoNome.getText()+" ?" , //Object message,
                                       "Confirmação de Cadastro", //String title
                                       JOptionPane.YES_NO_OPTION, //int optionType
                                       JOptionPane.QUESTION_MESSAGE, //int messageType
                                       null, //Icon icon,
                                       null, //Object[] options,
                                       "");//Object initialValue 
        if(choice == 0 ){
            Data data = new Data();
            String Data = data.getDataAtual();
            Cliente clienteAdd = new Cliente(textoNome.getText().trim(),textoRGCPF.getText().trim(),textoTel.getText().trim(),textoCel.getText().trim(),textoEnd.getText().trim(),
                                        textoBairro.getText().trim(),textoNota.getText().trim(),Data);


            int n = JOptionPane.showConfirmDialog(this,"Deseja adicionar um serviço ao cliente "+textoNome.getText()+"?","Adicionar serviço?",JOptionPane.YES_NO_OPTION);
                
                if(n==0){
                    this.setVisible(false);
                    AdicionaServico nova = new AdicionaServico(principal,this,null,null,null,clienteAdd,-1,principal.clientes);
                    nova.setVisible(true);
                }
                else{
                    
                    principal.clientes.add(clienteAdd);

                    ManipuladorDeArquivos manip = new ManipuladorDeArquivos();
                    manip.salvarLista(principal.clientes);
                    
                    this.dispose();
                    principal.atualizaUltimosClientes();
                    principal.setVisible(true);
                    }
        }
    }


        
        
        
        
        /*ArrayList<String> listaLinhas = new ArrayList<String>();

        try {
            listaLinhas = ManipuladorDeArquivos.lerArquivoTexto("entrada.txt");
        } catch (IOException ex) {
            Logger.getLogger(Janela1.class.getName()).log(Level.SEVERE, null, ex);
        }

        textoNome.setText((CatalogoClientes.interpretadorDeLinha(listaLinhas.get(0))).getNome());
        textoTel.setText((CatalogoClientes.interpretadorDeLinha(listaLinhas.get(0))).getTelefone());
        */
    }//GEN-LAST:event_botaoAddClienteActionPerformed
    //Ação ao clicar em voltar.
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed

        if((textoNome.getText()).isEmpty() && (textoTel.getText()).isEmpty() && (textoCel.getText()).isEmpty() && (textoEnd.getText()).isEmpty() && (textoNota.getText()).isEmpty() && (textoRGCPF.getText()).isEmpty())
        {
            this.dispose();
            principal.setVisible(true);
        }
        else
        {
            int choice = JOptionPane.showOptionDialog(null, //Component parentComponent
                               "Deseja realmente voltar ?" , //Object message,
                               "Confirmar cancelamento de registro.", //String title
                               JOptionPane.YES_NO_OPTION, //int optionType
                               JOptionPane.QUESTION_MESSAGE, //int messageType
                               null, //Icon icon,
                               null, //Object[] options,
                               "");//Object initialValue 
            if(choice==0)
            {
            this.dispose();
            principal.setVisible(true);
            }
        
        }
                
        
        
    }//GEN-LAST:event_botaoVoltarActionPerformed
    
    //Evita colocar ";" no campo de gasto, substituindo por ponto sempre.
    private void textoRGCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoRGCPFKeyTyped
        char c = evt.getKeyChar();
         
        if( c == 44 )
            
            evt.setKeyChar('.');
    }//GEN-LAST:event_textoRGCPFKeyTyped
    
    //Oque acontece quando aperta botão de fechar janela.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();  
        principal.setVisible(true);
       
    }//GEN-LAST:event_formWindowClosing

    private void textoTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTelKeyTyped
        String caracteres="0987654321-.)(";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_textoTelKeyTyped

    private void textoCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoCelKeyTyped
        String caracteres="0987654321-.)(";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_textoCelKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdicionaContatoJanela().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddCliente;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textoBairro;
    private javax.swing.JTextField textoCel;
    private javax.swing.JTextField textoEnd;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextArea textoNota;
    private javax.swing.JTextField textoRGCPF;
    private javax.swing.JTextField textoTel;
    // End of variables declaration//GEN-END:variables
}
