/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteEstofaria;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


public class FichaServicos extends javax.swing.JFrame {
    ArrayList<Servico> lista;
    ArrayList<Cliente> listaClientes;
    Principal principal;
    Ficha ficha;
    int posicao;
    
    public FichaServicos(Principal pri,ArrayList<Servico> lis,Ficha fi,int pos,ArrayList<Cliente> listaC) {
        initComponents();
        this.lista = lis;
        this.principal = pri;
        ficha = fi;
        posicao = pos;
        listaClientes = listaC;
        DefaultTableModel tabela = (DefaultTableModel) tabelaServicos.getModel();
        for(Servico X: lista){
        String[] dataFinal = X.getData().replace(" de ", "/").split("--");
        tabela.addRow(new String[] {X.getTrabalho(),X.getValorCobrado(),X.getValorGasto(),dataFinal[0]});
        this.setSize(510, 340);
        ImageIcon img = new ImageIcon("src/Icons/iconsofa.png");
        this.setIconImage(img.getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaServicos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoNotaServico = new javax.swing.JTextArea();
        botaoAddServico = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        janelaServicos.setBackground(new java.awt.Color(204, 204, 204));
        janelaServicos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        janelaServicos.setLayout(null);

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviço", "Valor Cobrado", "Valor Gasto", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaServicos.setSelectionBackground(new java.awt.Color(255, 255, 153));
        tabelaServicos.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tabelaServicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaServicos.getTableHeader().setReorderingAllowed(false);
        tabelaServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaServicos);
        tabelaServicos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaServicos.getColumnModel().getColumnCount() > 0) {
            tabelaServicos.getColumnModel().getColumn(0).setResizable(false);
            tabelaServicos.getColumnModel().getColumn(0).setPreferredWidth(70);
            tabelaServicos.getColumnModel().getColumn(1).setResizable(false);
            tabelaServicos.getColumnModel().getColumn(1).setPreferredWidth(15);
            tabelaServicos.getColumnModel().getColumn(2).setResizable(false);
            tabelaServicos.getColumnModel().getColumn(2).setPreferredWidth(15);
            tabelaServicos.getColumnModel().getColumn(3).setResizable(false);
            tabelaServicos.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        janelaServicos.add(jScrollPane1);
        jScrollPane1.setBounds(11, 12, 488, 157);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Anotações do serviço selecionado:");
        janelaServicos.add(jLabel1);
        jLabel1.setBounds(11, 175, 210, 23);

        textoNotaServico.setEditable(false);
        textoNotaServico.setColumns(20);
        textoNotaServico.setRows(5);
        jScrollPane2.setViewportView(textoNotaServico);

        janelaServicos.add(jScrollPane2);
        jScrollPane2.setBounds(11, 204, 488, 125);

        botaoAddServico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAddServico.setText("Adicionar Serviço");
        botaoAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddServicoActionPerformed(evt);
            }
        });
        janelaServicos.add(botaoAddServico);
        botaoAddServico.setBounds(362, 175, 137, 23);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 340);

        janelaServicos.add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaServicos, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaServicos, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaServicosMouseClicked
        int x= tabelaServicos.getSelectedRow();
        
        textoNotaServico.setText(lista.get(x).getComentarioAdicional());
    }//GEN-LAST:event_tabelaServicosMouseClicked

    private void botaoAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddServicoActionPerformed
        this.dispose();
        ficha.dispose();
        ficha.botaoMostrarServicos.setSelected(false);
        ficha.botaoMostrarServicos.setText("Mostrar Serviços");
        AdicionaServico add = new AdicionaServico(principal,null,ficha,null,null,listaClientes.get(posicao),posicao,listaClientes);
        add.setVisible(true);
        add.setLocationRelativeTo(this);
    }//GEN-LAST:event_botaoAddServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JanelaFichaServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel janelaServicos;
    private javax.swing.JTable tabelaServicos;
    private javax.swing.JTextArea textoNotaServico;
    // End of variables declaration//GEN-END:variables
}
