/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteEstofaria;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


public class ListarClientes extends javax.swing.JFrame {
    Principal principal;
    Cliente clienteSelecionado;
    ArrayList<Cliente> lista;
    ArrayList<Cliente> listaOrdenada;
    ArrayList<Integer> listaAchadaIndexes;
    
    public ListarClientes(Principal pri,ArrayList<Cliente> cli) {
        initComponents();
        this.principal = pri;
        this.lista = cli;
       
        listaOrdenada = new ArrayList();
        listaAchadaIndexes = new ArrayList();
        
        for(int x=lista.size()-1;x>=0;x--){
            this.listaOrdenada.add(this.lista.get(x));
            this.listaAchadaIndexes.add(x);
        }
        this.setSize(1025, 445);
   
        preencheTabela(this.listaOrdenada);
        
        ImageIcon img = new ImageIcon("src/Icons/iconsofa.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        verFichaCompletaAchados = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botaoAddServicoListados = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientesListados = new javax.swing.JTable();
        ordenaNome = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        ordenaEndereco = new javax.swing.JRadioButton();
        ordenaBairro = new javax.swing.JRadioButton();
        ordenaData = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Listar Clientes");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 125, 1020, 10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes Encontrados:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 145, 133, 19);

        verFichaCompletaAchados.setText("Ver ficha completa do cliente selecionado");
        verFichaCompletaAchados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFichaCompletaAchadosActionPerformed(evt);
            }
        });
        getContentPane().add(verFichaCompletaAchados);
        verFichaCompletaAchados.setBounds(752, 141, 260, 23);

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Listar Clientes");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-9, 11, 1040, 43);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 65, 1020, 10);

        botaoAddServicoListados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAddServicoListados.setText("Adicionar Serviço");
        botaoAddServicoListados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddServicoListadosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAddServicoListados);
        botaoAddServicoListados.setBounds(850, 378, 160, 32);

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Seta Voltar.png"))); // NOI18N
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(10, 378, 79, 32);

        tabelaClientesListados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Identificação", "Endereço", "Bairro", "Telefone", "Celular", "Nº de Serviços", "Data Adicionado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientesListados.setSelectionBackground(new java.awt.Color(255, 255, 153));
        tabelaClientesListados.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tabelaClientesListados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaClientesListados);
        if (tabelaClientesListados.getColumnModel().getColumnCount() > 0) {
            tabelaClientesListados.getColumnModel().getColumn(0).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaClientesListados.getColumnModel().getColumn(1).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(1).setPreferredWidth(25);
            tabelaClientesListados.getColumnModel().getColumn(2).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(2).setPreferredWidth(90);
            tabelaClientesListados.getColumnModel().getColumn(3).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(3).setPreferredWidth(20);
            tabelaClientesListados.getColumnModel().getColumn(4).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(4).setPreferredWidth(15);
            tabelaClientesListados.getColumnModel().getColumn(5).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(5).setPreferredWidth(15);
            tabelaClientesListados.getColumnModel().getColumn(6).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(6).setPreferredWidth(1);
            tabelaClientesListados.getColumnModel().getColumn(7).setResizable(false);
            tabelaClientesListados.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 1000, 202);

        ordenaNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordenaNome.setForeground(new java.awt.Color(255, 255, 255));
        ordenaNome.setText("Nome");
        ordenaNome.setOpaque(false);
        ordenaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(ordenaNome);
        ordenaNome.setBounds(10, 99, 70, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ordenar Por:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 76, 120, 17);

        ordenaEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordenaEndereco.setForeground(new java.awt.Color(255, 255, 255));
        ordenaEndereco.setText("Endereço");
        ordenaEndereco.setOpaque(false);
        ordenaEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(ordenaEndereco);
        ordenaEndereco.setBounds(116, 99, 90, 23);

        ordenaBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordenaBairro.setForeground(new java.awt.Color(255, 255, 255));
        ordenaBairro.setText("Bairro");
        ordenaBairro.setOpaque(false);
        ordenaBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaBairroActionPerformed(evt);
            }
        });
        getContentPane().add(ordenaBairro);
        ordenaBairro.setBounds(233, 99, 70, 23);

        ordenaData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordenaData.setForeground(new java.awt.Color(255, 255, 255));
        ordenaData.setSelected(true);
        ordenaData.setText("Data Adicionado");
        ordenaData.setOpaque(false);
        ordenaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaDataActionPerformed(evt);
            }
        });
        getContentPane().add(ordenaData);
        ordenaData.setBounds(332, 99, 130, 23);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1030, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAddServicoListadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddServicoListadosActionPerformed
        
        int x = this.tabelaClientesListados.getSelectedRow();
        
        if(x>=0){
            this.dispose();
            clienteSelecionado = listaOrdenada.get(this.tabelaClientesListados.getSelectedRow());
            x = lista.indexOf(clienteSelecionado);
            AdicionaServico add = new AdicionaServico(principal,null,null,null,this,clienteSelecionado,x,lista);
            add.setVisible(true);
            add.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_botaoAddServicoListadosActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void verFichaCompletaAchadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFichaCompletaAchadosActionPerformed
        
        int x = this.tabelaClientesListados.getSelectedRow();
        
        if(x >= 0){
            this.dispose();
            clienteSelecionado = listaOrdenada.get(this.tabelaClientesListados.getSelectedRow());
            x = lista.indexOf(clienteSelecionado);
            Ficha ficha = new Ficha(principal,null,this,clienteSelecionado,x,lista);
            ficha.setVisible(true);
            ficha.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_verFichaCompletaAchadosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void ordenaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaNomeActionPerformed
        listaOrdenada = new ArrayList();
        listaAchadaIndexes = new ArrayList();
        ordenaNome.setSelected(true);
        ordenaEndereco.setSelected(false);
        ordenaBairro.setSelected(false);
        ordenaData.setSelected(false);
        
        for(Cliente X:lista){
            listaOrdenada.add(X);
        }
        
        listaOrdenada.sort(new Comparator<Cliente>()
                 {
                     public int compare(Cliente p1, Cliente p2)
                     {
                         return p1.getNome().trim().toLowerCase().compareTo(p2.getNome().trim().toLowerCase());
                     }        
                 });
        
        preencheTabela(listaOrdenada);
        
    }//GEN-LAST:event_ordenaNomeActionPerformed

    private void ordenaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaEnderecoActionPerformed
        listaOrdenada = new ArrayList();
        listaAchadaIndexes = new ArrayList();
        ordenaNome.setSelected(false);
        ordenaEndereco.setSelected(true);
        ordenaBairro.setSelected(false);
        ordenaData.setSelected(false);
        
        for(Cliente X:lista){
            listaOrdenada.add(X);
        }
        
        listaOrdenada.sort(new Comparator<Cliente>()
                 {
                     public int compare(Cliente p1, Cliente p2)
                     {
                         return p1.getEndereco().trim().toLowerCase().compareTo(p2.getEndereco().trim().toLowerCase());
                     }        
                 });
        
        preencheTabela(listaOrdenada);
        
    }//GEN-LAST:event_ordenaEnderecoActionPerformed

    private void ordenaBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaBairroActionPerformed
        listaOrdenada = new ArrayList();
        listaAchadaIndexes = new ArrayList();
        ordenaNome.setSelected(false);
        ordenaEndereco.setSelected(false);
        ordenaBairro.setSelected(true);
        ordenaData.setSelected(false);
        
        for(Cliente X:lista){
            listaOrdenada.add(X);
        }
        
        listaOrdenada.sort(new Comparator<Cliente>()
                 {
                     public int compare(Cliente p1, Cliente p2)
                     {
                         return p1.getBairro().trim().toLowerCase().compareTo(p2.getBairro().trim().toLowerCase());
                     }        
                 });
        
        preencheTabela(listaOrdenada);
        
        
    }//GEN-LAST:event_ordenaBairroActionPerformed

    private void ordenaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaDataActionPerformed
        listaOrdenada = new ArrayList();
        listaAchadaIndexes = new ArrayList();
        ordenaNome.setSelected(false);
        ordenaEndereco.setSelected(false);
        ordenaBairro.setSelected(false);
        ordenaData.setSelected(true);
        
        for(int x=lista.size()-1;x>=0;x--){
            this.listaOrdenada.add(this.lista.get(x));
        }
        
        preencheTabela(listaOrdenada);
        
    }//GEN-LAST:event_ordenaDataActionPerformed
    
    private void preencheTabela(ArrayList<Cliente> lista){
      
        DefaultTableModel tabela = (DefaultTableModel) tabelaClientesListados.getModel();
         
        while(tabelaClientesListados.getRowCount()>0){
            tabela.removeRow(0);
        } 
        
         for(Cliente X : lista){
             String[] dataFinal; 
             dataFinal = X.getDataAdd().replace(" de ", "/").split("--");
             tabela.addRow(new String[] {X.getNome(),X.getID(),X.getEndereco(),X.getBairro(),X.getTelefone(),X.getCelular(),String.valueOf(X.getServicos().size()),dataFinal[0]});
         }
         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddServicoListados;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton ordenaBairro;
    private javax.swing.JRadioButton ordenaData;
    private javax.swing.JRadioButton ordenaEndereco;
    private javax.swing.JRadioButton ordenaNome;
    private javax.swing.JTable tabelaClientesListados;
    private javax.swing.JButton verFichaCompletaAchados;
    // End of variables declaration//GEN-END:variables
}
