
package PacoteEstofaria;


import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;


public class Principal extends javax.swing.JFrame  {
    public ArrayList<Cliente> clientes;
    
    public Principal() {
        initComponents();
        ManipuladorDeArquivos manip = new ManipuladorDeArquivos();
        manip.preBackup();   
        this.clientes = manip.carregarLista(); 
        atualizaUltimosClientes();
        
        this.setSize(555, 458);
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("src/Icons/iconsofa.png");
        this.setIconImage(img.getImage());  
    } 
    
    
    protected void paintComponent(Graphics g){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAdicionarCliente = new javax.swing.JButton();
        labelMenu = new javax.swing.JLabel();
        botaoProcurarCliente = new javax.swing.JButton();
        botaoAdicionarClientes = new javax.swing.JButton();
        botaoAdicionarServico = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        botaoFichaPrincipal = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botaoExpandir = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estofaria Rojas");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        botaoAdicionarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAdicionarCliente.setText("Adicionar Cliente");
        botaoAdicionarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionarCliente);
        botaoAdicionarCliente.setBounds(15, 122, 210, 45);

        labelMenu.setFont(new java.awt.Font("Lucida Sans", 3, 46)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(204, 255, 255));
        labelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu.setText("Estofaria Rojas");
        labelMenu.setToolTipText("");
        labelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(labelMenu);
        labelMenu.setBounds(-2, 15, 560, 70);

        botaoProcurarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoProcurarCliente.setText("Procurar Cliente");
        botaoProcurarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcurarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoProcurarCliente);
        botaoProcurarCliente.setBounds(15, 178, 210, 45);

        botaoAdicionarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAdicionarClientes.setText("Listar Clientes");
        botaoAdicionarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoAdicionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionarClientes);
        botaoAdicionarClientes.setBounds(15, 234, 210, 45);

        botaoAdicionarServico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAdicionarServico.setText("Adicionar Serviço");
        botaoAdicionarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoAdicionarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionarServico);
        botaoAdicionarServico.setBounds(15, 290, 210, 45);

        botaoSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair);
        botaoSair.setBounds(15, 346, 210, 45);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Últimos Clientes adicionados:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(297, 101, 199, 17);

        listaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listaClientes.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        listaClientes.setForeground(new java.awt.Color(0, 51, 51));
        listaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaClientes.setSelectionBackground(new java.awt.Color(255, 255, 153));
        listaClientes.setSelectionForeground(new java.awt.Color(0, 0, 255));
        listaClientes.setVisibleRowCount(5);
        listaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaClientes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(243, 122, 295, 235);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 95, 548, 10);

        botaoFichaPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoFichaPrincipal.setText("Mostrar ficha do cliente selecionado");
        botaoFichaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFichaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFichaPrincipal);
        botaoFichaPrincipal.setBounds(243, 363, 295, 28);

        panelPrincipal.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);
        panelPrincipal.add(jPanel1);
        jPanel1.setBounds(10, 440, 530, 180);

        botaoExpandir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botaoExpandir.setText("Mostrar mais...");
        botaoExpandir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExpandirActionPerformed(evt);
            }
        });
        panelPrincipal.add(botaoExpandir);
        botaoExpandir.setBounds(-10, 410, 570, 21);
        panelPrincipal.add(jSeparator2);
        jSeparator2.setBounds(0, 410, 550, 10);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.jpg"))); // NOI18N
        panelPrincipal.add(imagemFundo);
        imagemFundo.setBounds(0, 0, 550, 630);

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(0, 0, 550, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Oque acontece quando clica em Adicionar Cliente no menu principal.
    private void botaoAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarClienteActionPerformed
        this.setVisible(false);
        
        AdicionaContato add = new AdicionaContato(this);
        add.setVisible(true);
        add.setLocationRelativeTo(this);
      
    }//GEN-LAST:event_botaoAdicionarClienteActionPerformed

//GEN-FIRST:event_botaoFichaPrincipalActionPerformed
    private void botaoFichaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {
        int x = listaClientes.getSelectedIndex();
        ArrayList<Cliente> ListaClientes = this.clientes;
        int Qtnd = ListaClientes.size();

        if(x>=0){
        x=x+1;
            if(x <= Qtnd){
                this.setVisible(false);
                Ficha janela = new Ficha(this,null,null,ListaClientes.get(Qtnd-x),clientes.size()-x,clientes);
                janela.setVisible(true);
                janela.setLocationRelativeTo(this);

                
             }
        }
//GEN-LAST:event_botaoFichaPrincipalActionPerformed
    }
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        ManipuladorDeArquivos manip = new ManipuladorDeArquivos();
        manip.criaBackup(this.clientes);
        
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcurarClienteActionPerformed
        this.setVisible(false);
        ProcurarCliente procura = new ProcurarCliente(this,clientes,0);
        procura.setLocationRelativeTo(this);
        procura.setVisible(true);
    }//GEN-LAST:event_botaoProcurarClienteActionPerformed

    private void botaoAdicionarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarServicoActionPerformed
        this.setVisible(false);
        ProcurarCliente procura = new ProcurarCliente(this,clientes,1);
        procura.setLocationRelativeTo(this);
        procura.setVisible(true);
    }//GEN-LAST:event_botaoAdicionarServicoActionPerformed

    private void botaoAdicionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarClientesActionPerformed
        ListarClientes listar = new ListarClientes(this,clientes);
        this.setVisible(false);
        listar.setVisible(true);
        listar.setLocationRelativeTo(this);
    }//GEN-LAST:event_botaoAdicionarClientesActionPerformed

    private void botaoExpandirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExpandirActionPerformed
        if(!botaoExpandir.isSelected()){
            int y= this.getSize().height;
            botaoExpandir.setText("Mostrar mais...");

            this.setSize(this.getSize().width, y-200);
            this.setLocation(this.getLocation().x,this.getLocation().y+100);
        }else{
            int y= this.getSize().height;
            botaoExpandir.setText("Mostrar menos...");
            this.setLocation(this.getLocation().x, this.getLocation().y-200);
            
            if(this.getLocation().y < 0)
                this.setLocation(this.getLocation().x, 20);
            
            this.setSize(this.getSize().width, y+200);
        }
    }//GEN-LAST:event_botaoExpandirActionPerformed

    private void listaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaClientesMouseClicked
        if(evt.getClickCount() == 2){
            int x = listaClientes.getSelectedIndex();
            ArrayList<Cliente> ListaClientes = this.clientes;
            int Qtnd = ListaClientes.size();

            if(x>=0){
            x=x+1;
                if(x <= Qtnd){
                    this.setVisible(false);
                    Ficha janela = new Ficha(this,null,null,ListaClientes.get(Qtnd-x),clientes.size()-x,clientes);
                    janela.setVisible(true);
                    janela.setLocationRelativeTo(this);


                 }
            }
        }
    }//GEN-LAST:event_listaClientesMouseClicked
    
   
    //------------------------------------------------------------------------------Lista de opções menu principal.
    
    public void atualizaUltimosClientes(){
        ArrayList<Cliente> ListaClientes = this.clientes;
                
                int QtndLinhas = ListaClientes.size();
                
                DefaultListModel model = new DefaultListModel();
               
                if(QtndLinhas < 1)
                model.addElement("  ---------------------------");
                else
                model.addElement((ListaClientes.get(QtndLinhas-1)).getNome());
                
               if(QtndLinhas < 2)
                model.addElement("  ---------------------------");
                else
                model.addElement((ListaClientes.get(QtndLinhas-2)).getNome());
                
               if(QtndLinhas < 3)
                model.addElement("  ---------------------------");
                else
                model.addElement((ListaClientes.get(QtndLinhas-3)).getNome());
                
               if(QtndLinhas < 4)
                model.addElement("  ---------------------------");
                else
                model.addElement((ListaClientes.get(QtndLinhas-4)).getNome());
                
               if(QtndLinhas < 5)
                model.addElement("  ---------------------------");
                else
                model.addElement((ListaClientes.get(QtndLinhas-5)).getNome());
                
               listaClientes.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarCliente;
    private javax.swing.JButton botaoAdicionarClientes;
    private javax.swing.JButton botaoAdicionarServico;
    private javax.swing.JToggleButton botaoExpandir;
    private javax.swing.JButton botaoFichaPrincipal;
    private javax.swing.JButton botaoProcurarCliente;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelMenu;
    private static javax.swing.JList<String> listaClientes;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}

